  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
          -
            AttributeName: creatorId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          -
            IndexName: ${self:provider.environment.USERS_TABLE_CREATORID_INDEX}
            KeySchema:
              -
                AttributeName: creatorId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.usersTableName}
    AssetTransactionsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: uniqueAssetId
            AttributeType: S
          -
            AttributeName: blockchainRecordId
            AttributeType: S
          -
            AttributeName: ethAddress
            AttributeType: S
        KeySchema:
          -
            AttributeName: uniqueAssetId
            KeyType: HASH
          -
            AttributeName: blockchainRecordId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
         -
            IndexName: ${self:provider.environment.ASSETTRANSACTIONS_TABLE_ETHADDRESS_INDEX}
            KeySchema:
              -
                AttributeName: ethAddress
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:custom.assetTransactionsTableName}
    ApiKeysDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: apiKey
            AttributeType: S
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: apiKey
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          -
            IndexName: ${self:provider.environment.APIKEYS_TABLE_USERID_INDEX}
            KeySchema:
              -
                AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:custom.apiKeysTableName}
    MetaDataBicycleTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: uniqueAssetId
            AttributeType: S
          -
            AttributeName: vendor
            AttributeType: S
          -
            AttributeName: serialNumber
            AttributeType: S
          -
            AttributeName: frameNumber
            AttributeType: S
        KeySchema:
          -
            AttributeName: uniqueAssetId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          -
            IndexName: ${self:provider.environment.METADATABICYCLES_TABLE_FRAMENUMBER_INDEX}
            KeySchema:
              -
                AttributeName: frameNumber
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          -
            IndexName: ${self:provider.environment.METADATABICYCLES_TABLE_VENDOR_INDEX}
            KeySchema:
              -
                AttributeName: vendor
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          -
            IndexName: ${self:provider.environment.METADATABICYCLES_TABLE_SERIALNUMBER_INDEX}
            KeySchema:
              -
                AttributeName: serialNumber
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:custom.metaDataBicycleTableName}